require:
  - rubocop-performance

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

AllCops:
  TargetRubyVersion: 2.6.5
  DisplayCopNames: true